name: Daily Sign-in

on:
  # 每天执行一次
  schedule:
    - cron: '0 0 * * *'  # UTC 时间0点，对应北京时间早上8点
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run sign script
        run: python sign.py
        env:
          # 从GitHub仓库的Secrets获取账号密码
          HEYBOX_ACCOUNT: ${{ secrets.HEYBOX_ACCOUNT }}
          HEYBOX_PASSWORD: ${{ secrets.HEYBOX_PASSWORD }}
